dist: trusty

language: cpp

compiler:
    - clang
    - gcc

dist: trusty

before_install:
    # cmake 3.2
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y

    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

    - sudo apt-get update -qq

install:
    # cmake 3.2
    - sudo apt-get install cmake cmake-data

    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - ./bin/ratlesnake --help

notifications:
    email:
        on_success: change
        on_failure: always
